name: Operator Onboarding

on:
  issues:
    types: [opened, edited]

jobs:
  update-ibc-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create Necessary Directories
        run: mkdir -p ../_IBC || true

      - name: Check if issue has operator-onboarding label
        id: label-check
        run: |
          LABELS_JSON='${{ toJson(github.event.issue.labels) }}'
          LABEL=$(echo $LABELS_JSON | jq -r '.[] | select(.name == "operator-onboarding").name')
          if [ "$LABEL" == "operator-onboarding" ]; then
            echo "LABEL_FOUND=true" >> $GITHUB_ENV
          else
            echo "LABEL_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Update IBC file and create PR
        if: env.LABEL_FOUND == 'true'
        run: python ./scripts/update_ibc_file.py ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
